import type { Locale } from "./i18n";

export const AUTHOR_NAMES_AR: Record<string, string> = {
  "adel-zekri": "د. عادل زكري",
  "amir-nasr": "أ. أمير نصر",
  "anba-angelos": "الأنبا أنجيلوس",
  "anba-bimen": "الأنبا بيمن أسقف ملوي",
  "anba-bishoy": "الأنبا بيشوي",
  "anba-demetrius": "الأنبا ديمتريوس أسقف ملوي",
  "anba-macarious": "الأنبا مكاريوس الأسقف العام بالمنيا",
  "anba-metaos": "الأنبا متاؤس أسقف دير السريان",
  "anba-raphael": "الأنبا رافائيل الأسقف العام لكنائس وسط القاهرة",
  "anba-yoannes": "الأنبا يوأنس أسقف الغربية",
  "bishop-isithoros": "الأسقف إيسيذورس",
  "bishop-moussa": "الأنبا موسى أسقف الشباب",
  "bishop-yakobos": "الأنبا ياكوبوس",
  "church-books": "كتب الكنيسة",
  "church-fathers": "آباء الكنيسة",
  "ebooks": "كتب متنوعة",
  "ecf": "آباء الكنيسة الأوائل",
  "engeel-yahouza": "القمص عبد المسيح بسيط أبو الخير",
  "fady-nabil": "د. فادي نبيل",
  "father-abdel-messih-basiet-abo-el-kheir": "القمص عبد المسيح بسيط أبو الخير",
  "father-bishoy-kamel": "القمص بيشوي كامل",
  "fr-angelos-almaqary": "القمص أنجيلوس المقاري",
  "fr-athnasius-fahmy": "القمص أثناسيوس فهمي جورج",
  "fr-bishoy-abdel-massih-z": "القمص بيشوي عبد المسيح",
  "fr-bishoy-fayek": "القس بيشوي فايق",
  "fr-boles-milad": "القس بولس ميلاد يوسف",
  "fr-botros-elbaramosy": "القمص بطرس البراموسي",
  "fr-dawood-lamey": "القمص داود لمعي",
  "fr-matthias-farid": "القمص متياس فريد وهبة",
  "fr-maximos-samuel": "القس مكسيموس صموئيل",
  "fr-morcos-dawoud": "القمص مرقس داود",
  "fr-pakhomius-marcos": "القس باخوميوس القمص مرقص جبرة",
  "fr-raphael-nasr": "القمص رافائيل نصر",
  "fr-salaib-hakim": "القمص صليب حكيم",
  "fr-sarafim-elbaramousy": "الراهب سارافيم البرموسي",
  "fr-tadros-malaty": "القمص تادرس يعقوب ملطي",
  "fr-yoannes-st-paul": "القمص يوأنس الأنبا بولا",
  "fr-youhanna-fayez": "القمص يوحنا فايز زخاري",
  "habib-guirguis": "القديس الأرشيذياكون حبيب جرجس",
  "helmy-elkommos": "أ. حلمي القمص يعقوب",
  "iris-habib-elmasry": "أ. إيريس حبيب المصري",
  "is-there-a-new-prophet-after-jesus": "القمص عبد المسيح بسيط أبو الخير",
  "iskander-hanna": "أ. إسكندر حنا",
  "katamars": "القطمارس",
  "lyrics": "ألحان وأناشيد",
  "maurice-tawadrous": "موريس تواضروس",
  "nagwa-ghazaly": "أ. نجوى غزالي",
  "nagy-gayed": "أ. ناجي جيد",
  "pauline-todary": "أ. بولين تودري",
  "pope-shenouda-iii": "قداسة البابا شنودة الثالث",
  "roshdi-wasef-bahman-dous": "رشدي واصف بهمان دوس",
  "shepherd-voice": "مطبوعات صوت الراعي",
  "sts-church-sidi-beshr": "كنيسة القديسين بسيدي بشر",
  "synaxarium-or-synaxarion": "السنكسار",
  "the-da-vinci-code-exposed": "القمص عبد المسيح بسيط أبو الخير",
  "various": "مؤلفون متنوعون",
  "various-authors": "مؤلفون متنوعون",
  "victor-beshir": "الشماس فيكتور بشير",
  "youssef-habib": "يوسف حبيب",
};

export const AUTHOR_NAMES_EN: Record<string, string> = {
  "adel-zekri": "Dr. Adel Zekry",
  "amir-nasr": "Amir Nasr",
  "anba-angelos": "H.G. Bishop Angelos",
  "anba-bimen": "H.G. Bishop Bemen of Mallawi",
  "anba-bishoy": "H.G. Metropolitan Bishoy",
  "anba-demetrius": "H.G. Bishop Demetrius of Mallawi",
  "anba-macarious": "H.G. Bishop Macarius of Minya",
  "anba-metaos": "H.G. Bishop Metaos of Deir El-Surian",
  "anba-raphael": "H.G. Bishop Raphael",
  "anba-yoannes": "H.G. Bishop Youannes of Gharbia",
  "bishop-isithoros": "Bishop Isithoros",
  "bishop-moussa": "H.G. Bishop Moussa, Bishop of Youth",
  "bishop-yakobos": "H.G. Bishop Yakobos",
  "church-books": "Church Books",
  "church-fathers": "Church Fathers",
  "ebooks": "Various Authors",
  "ecf": "Early Church Fathers",
  "engeel-yahouza": "Fr. Abd El-Messih Basit Abu El-Khair",
  "fady-nabil": "Dr. Fady Nabil",
  "father-abdel-messih-basiet-abo-el-kheir": "Fr. Abd El-Messih Basit Abu El-Khair",
  "father-bishoy-kamel": "Fr. Bishoy Kamel",
  "fr-angelos-almaqary": "Fr. Angelos El-Makary",
  "fr-athnasius-fahmy": "Fr. Athanasius Fahmy George",
  "fr-bishoy-abdel-massih-z": "Fr. Bishoy Abd El-Messih",
  "fr-bishoy-fayek": "Fr. Bishoy Fayek",
  "fr-boles-milad": "Fr. Boules Milad Youssef",
  "fr-botros-elbaramosy": "Fr. Boutros El-Baramosy",
  "fr-dawood-lamey": "Fr. Daoud Lamei",
  "fr-matthias-farid": "Fr. Matthias Farid Wahba",
  "fr-maximos-samuel": "Fr. Maximos Samuel",
  "fr-morcos-dawoud": "Fr. Morcos Daoud",
  "fr-pakhomius-marcos": "Fr. Pakhomius Marcos",
  "fr-raphael-nasr": "Fr. Raphael Nasr",
  "fr-salaib-hakim": "Fr. Salib Hakim",
  "fr-sarafim-elbaramousy": "Fr. Serapheim El-Baramousy",
  "fr-tadros-malaty": "Fr. Tadros Y. Malaty",
  "fr-yoannes-st-paul": "Fr. Youannes of St. Paul Monastery",
  "fr-youhanna-fayez": "Fr. Youhanna Fayez Zakhary",
  "habib-guirguis": "St. Habib Guirguis",
  "helmy-elkommos": "Helmy El-Kommos Yacoub",
  "iris-habib-elmasry": "Iris Habib El-Masry",
  "is-there-a-new-prophet-after-jesus": "Fr. Abd El-Messih Basit Abu El-Khair",
  "iskander-hanna": "Iskandar Hanna",
  "katamars": "Katameros",
  "lyrics": "Hymns & Lyrics",
  "maurice-tawadrous": "Maurice Tadros",
  "nagwa-ghazaly": "Nagwa Ghazaly",
  "nagy-gayed": "Nagy Gayed",
  "pauline-todary": "Pauline Todary",
  "pope-shenouda-iii": "H.H. Pope Shenouda III",
  "roshdi-wasef-bahman-dous": "Roshdi Wasef Bahman Dous",
  "shepherd-voice": "Shepherd's Voice Publications",
  "sts-church-sidi-beshr": "Sts. Church, Sidi Bishr (Alexandria)",
  "synaxarium-or-synaxarion": "Synaxarium",
  "the-da-vinci-code-exposed": "Fr. Abd El-Messih Basit Abu El-Khair",
  "various": "Various Authors",
  "various-authors": "Various Authors",
  "victor-beshir": "Deacon Victor Beshir",
  "youssef-habib": "Youssef Habib",
};

const PREFIXES = [
  /^(ترجمة|إعداد|تعريب|إعداد ودراسة|بقلم|تأليف|اعداد)\s*[:،]\s*/u,
  /^(ترجمة|إعداد|تعريب|اعداد)\s+/u,
];

export function cleanAuthorName(raw: string): string {
  let name = raw.trim();
  for (const re of PREFIXES) name = name.replace(re, "");
  return name.trim();
}

export function authorDisplayName(
  slug: string,
  fallback: string,
  locale: Locale = "ar",
): string {
  if (locale === "en") {
    return AUTHOR_NAMES_EN[slug] ?? cleanAuthorName(fallback);
  }
  return AUTHOR_NAMES_AR[slug] ?? cleanAuthorName(fallback);
}
